USE hadobo;

-- STUDENT Data

INSERT INTO STUDENT VALUES (
	1, 'Miracle Arewa', 14, 'Male');
INSERT INTO STUDENT VALUES (
	2, 'Bola Mystery', 17, 'Male');
INSERT INTO STUDENT VALUES (
	3, 'Bimbo Comfort', 19, 'Female');
INSERT INTO STUDENT VALUES (
	4, 'John Dan', 15, 'Male');
INSERT INTO STUDENT VALUES (
	5, 'Femi Jacob', 18, 'Male');
INSERT INTO STUDENT VALUES (
	6, 'Duni Pablo', 16, 'Female');


-- COURSE Data

INSERT INTO COURSE (title, facilitator, num_of_students)
	VALUES
	('Java 101', 'Jenny Loop', 6),
    ('Data Science 101', 'Evans Scale', 6),
    ('Critical Thinking 101', 'Sam Emma', 6),
    ('Python 101', 'Sikiru List', 6),
    ('Industrial Thinking 101', 'Dapo Control', 6),
    ('JavaScript 101', 'Chinedu Okwaya', 6),
    ('Design Thinking 101', 'Kim Feedback', 6),
    ('HTML and CSS 101', 'Chinedu Okwaya', 6),
    ('Database 101', 'Esther Mysql', 6),
    ('General Knowledge 101', 'Chibuzo Task', 6);
    
    
    -- GRADE Data

INSERT INTO GRADE VALUES (
	1, 1, 74);
INSERT INTO GRADE VALUES (
	2, 1, 54);
INSERT INTO GRADE VALUES (
	3, 1, 44);
INSERT INTO GRADE VALUES (
	4, 1, 85);
INSERT INTO GRADE VALUES (
	5, 1, 74);
INSERT INTO GRADE VALUES (
	6, 1, 67);
INSERT INTO GRADE VALUES (
	1, 2, 83);
INSERT INTO GRADE VALUES (
	2, 2, 43);
INSERT INTO GRADE VALUES (
	3, 2, 54);
INSERT INTO GRADE VALUES (
	4, 2, 83);
INSERT INTO GRADE VALUES (
	5, 2, 75);
INSERT INTO GRADE VALUES (
	6, 2, 48);
INSERT INTO GRADE VALUES (
	1, 3, 88);
INSERT INTO GRADE VALUES (
	2, 3, 44);
INSERT INTO GRADE VALUES (
	3, 3, 60);
INSERT INTO GRADE VALUES (
	4, 3, 54);
INSERT INTO GRADE VALUES (
	5, 3, 69);
INSERT INTO GRADE VALUES (
	6, 3, 36);
INSERT INTO GRADE VALUES (
	1, 4, 94);
INSERT INTO GRADE VALUES (
	2, 4, 88);
INSERT INTO GRADE VALUES (
	3, 4, 56);
INSERT INTO GRADE VALUES (
	4, 4, 78);
INSERT INTO GRADE VALUES (
	5, 4, 57);
INSERT INTO GRADE VALUES (
	6, 4, 27);
INSERT INTO GRADE VALUES (
	1, 5, 93);
INSERT INTO GRADE VALUES (
	2, 5, 72);
INSERT INTO GRADE VALUES (
	3, 5, 26);
INSERT INTO GRADE VALUES (
	4, 5, 68);
INSERT INTO GRADE VALUES (
	5, 5, 48);
INSERT INTO GRADE VALUES (
	6, 5, 52);
INSERT INTO GRADE VALUES (
	1, 6, 91);
INSERT INTO GRADE VALUES (
	2, 6, 72);
INSERT INTO GRADE VALUES (
	3, 6, 88);
INSERT INTO GRADE VALUES (
	4, 6, 75);
INSERT INTO GRADE VALUES (
	5, 6, 55);
INSERT INTO GRADE VALUES (
	6, 6, 99);
INSERT INTO GRADE VALUES (
	1, 7, 77);
INSERT INTO GRADE VALUES (
	2, 7, 47);
INSERT INTO GRADE VALUES (
	3, 7, 81);
INSERT INTO GRADE VALUES (
	4, 7, 58);
INSERT INTO GRADE VALUES (
	5, 7, 35);
INSERT INTO GRADE VALUES (
	6, 7, 73);
INSERT INTO GRADE VALUES (
	1, 8, 44);
INSERT INTO GRADE VALUES (
	2, 8, 74);
INSERT INTO GRADE VALUES (
	3, 8, 72);
INSERT INTO GRADE VALUES (
	4, 8, 92);
INSERT INTO GRADE VALUES (
	5, 8, 57);
INSERT INTO GRADE VALUES (
	6, 8, 24);
INSERT INTO GRADE VALUES (
	1, 9, 44);
INSERT INTO GRADE VALUES (
	2, 9, 69);
INSERT INTO GRADE VALUES (
	3, 9, 94);
INSERT INTO GRADE VALUES (
	4, 9, 64);
INSERT INTO GRADE VALUES (
	5, 9, 68);
INSERT INTO GRADE VALUES (
	6, 9, 73);
INSERT INTO GRADE VALUES (
	1, 10, 77);
INSERT INTO GRADE VALUES (
	2, 10, 44);
INSERT INTO GRADE VALUES (
	3, 10, 57);
INSERT INTO GRADE VALUES (
	4, 10, 88);
INSERT INTO GRADE VALUES (
	5, 10, 65);
INSERT INTO GRADE VALUES (
	6, 10, 99);